---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: storage-credentials
  namespace: hermans-code-fileshare
spec:
  encryptedData:
    auth: AgCBXtv4Mnkb737xK7x06AUYMGdzI1qA9va7c8OX0js/7Pndc6ukmysimkVeFJsb8u7dBUmpXmExQslZEuiAY3BFDrL9qQOlIpU37gap+xLt8OXa9Ogx+sRe6gamFoWoAzkZTfqRhhQ7TAB8s6a5b9DbVrkcZg8nFTZgcSJFEIlcPyaySafiOYvg1mZ/qB1unPGjgJAxrDOxj87oWL5wisT3wuE4EDYzGG6CRVOgRiPrzfNsj3kkwCWHRlWXNmvfPCn+MSlFi/MaEERRnmGagt+xh7+0n8v/KOurswv76+/vpZy7he4eDd9wQFct9FbJNQsunjT79Yt+yBEMWnNftvl6OhQVKMKvjnwVAOlfvljGd17dExOTAe2hq55q6JPbPrAvnqEf3vNnITrhdc3qJDfRVnEOKNAXTeVqAMmEL5UdtRkYl8VKVvDTprnKMsNuSatCSQv3AizfR5PKu2MxVEnol60hB23uWkRjm1hg7pJNib3ah0262UjH1bikAtaEmVyIlHPRGhWXtpzzMC3OT+kzDh+gr4KG3JOd1p4kkHQBNDH+MW/6/9czV+Xm4As2s7ZDkIOjyufAnpzQ2gdZ//TNHXfqBmrGQdsVfrKDMw9Ta6G0q+V+1mHtPv9pUai3y1foQvS9lOhmw5hQos50nGXx76OLOn4I+y8DUHPrZrDW5Ijh5qSWxBX8xtBl1gYNQxIfLwGv8DKYgSO9PEugaAV+Oe7Koc0uYa3KkS09UeHwvrIWVvJxIRqd8suegUeW50NZSOZ9HnyeIi/hK4QLxbNtgmBzQY6JeW8Q2hmaf+UxzDOD89tGgXDXoM9zSmYnUR8PQcqcapSt
  template:
    metadata:
      name: storage-credentials
      namespace: hermans-code-fileshare
      labels:
        app.kubernetes.io/part-of: hermans-code-fileshare
