apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hermans-code-documents-extras.fullname" . }}
  labels:
    {{- include "hermans-code-documents-extras.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hermans-code-documents-extras.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hermans-code-documents-extras.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: protonmail-bridge
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CONTAINER_SMTP_PORT
              value: {{ .Values.env.CONTAINER_SMTP_PORT | quote }}
            - name: CONTAINER_IMAP_PORT
              value: {{ .Values.env.CONTAINER_IMAP_PORT | quote }}
          ports:
            - name: smtp
              containerPort: {{ .Values.container.smtpPort }}
              protocol: TCP
            - name: imap
              containerPort: {{ .Values.container.imapPort }}
              protocol: TCP
          volumeMounts:
            - name: mail-data
              mountPath: {{ .Values.persistence.mountPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: mail-data
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{ else }}{{ include "hermans-code-documents-extras.fullname" . }}-mail-data{{ end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}

