apiVersion: v1
kind: Service
metadata:
  name: {{ include "hermans-code-documents-extras.fullname" . }}
  labels:
    {{- include "hermans-code-documents-extras.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: imap
      port: {{ .Values.service.port }}
      targetPort: imap
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "hermans-code-documents-extras.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

