apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hermans-code-fileshare
  namespace: argocd
spec:
  project: hermans-code
  destination:
    server: "https://kubernetes.default.svc"
    namespace: hermans-code-fileshare
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://ldtteam.github.io/NginxWebDav/
      chart: nginx-web-dav
      targetRevision: "0.*"
      helm:
        releaseName: hermans-code-fileshare
        valuesObject:
          persistence:
            labels:
              recurring-job-group.longhorn.io/high-frequency: "enabled"
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: "nginx"
              cert-manager.io/cluster-issuer: letsencrypt-dns
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              external-dns.alpha.kubernetes.io/target: "cluster.ldtteam.com."
            hosts:
              - fileshare-new.hermans-code.com
            auth:
              enabled: true
              secretRef:
                name: storage-credentials
              realm: "hermans-code FileShare"
          autoscaling:
            enabled: true
    - repoURL: {{ .Values.repository.url }}
      path: hermans-code-charts/hermans-code-fileshare-extras
      targetRevision: HEAD