apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hermans-code-paperless
  namespace: argocd
spec:
  project: hermans-code
  destination:
    server: "https://kubernetes.default.svc"
    namespace: hermans-code-paperless
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://charts.worli.dev
      chart: paperless-ngx
      targetRevision: "0.*"
      helm:
        releaseName: hermans-code-paperless
        valuesObject:
          paperless:
            env:
              values:
                PAPERLESS_URL: "https://documents.hermans-code.com"
            ingress:
              enabled: true
              className: nginx
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-dns
                external-dns.alpha.kubernetes.io/target: cluster.ldtteam.com
                nginx.ingress.kubernetes.io/ssl-redirect: "true"
              hosts:
                - host: documents.hermans-code.com
                  paths:
                    - path: /
                      pathType: Prefix
              tls:
                - secretName: paperless-ngx-tls
                  hosts:
                    - documents.hermans-code.com
                    
    - repoURL: {{ .Values.repository.url }}
      path: hermans-code-charts/hermans-code-documents-extras
      targetRevision: HEAD
